### ISSUE TITLE
crowd.user.get(username, true) does not work after last update

### ISSUE THREAD

**Issue by kamanwu-oicr** [ghengeveld/atlassian-crowd-client#3]
Basing on the error mesage, 

I checked the file : models/attributes.js   --->    attributesArr.forEach 
attributesArr is NOT an array so that do NOT have forEach function.

I print out attributesArr, it is an object, NOT an array.

**Comment by alexashley** [comment]
@kamanwu-oicr You might try pinning your dependency to the previous version.

Looks like the issue is that the Crowd [api user response](https://docs.atlassian.com/atlassian-crowd/latest/REST/#usermanagement/1/user-getUser) has an `attributes` object with a single `attributes` key (seems redundant), so [this](https://github.com/ghengeveld/atlassian-crowd-client/blob/a276944a9a2ee6615b9e94e6d73bc73519375f21/src/client.js#L30) should be `data.attributes.attributes`. 

(Confusingly, the [`/user/attributes` endpoint](https://docs.atlassian.com/atlassian-crowd/latest/REST/#usermanagement/1/user-getUserAttributes) does **not** do this weird nesting, it's just a object with an `attributes` key and an array).

**Comment by ghengeveld** [comment]
Thanks for the catch. I should've thought this through a little more. It's obviously a breaking change.

I'm going to make a fix release to roll-back to the old user.attributes behavior, then release a v2 with the breaking change (including Alex' improvement).

**Comment by ghengeveld** [comment]
There's now a v1.5.1 which rolls back the attribute mapping on User. That should fix your issue @kamanwu-oicr.
